name: 'olist_dbt'
version: '1.0.0'
config-version: 2

profile: 'olist_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_dbt:
    bronze:
      +materialized: view
    silver:
      +materialized: table
      +file_format: parquet
    gold:
      +materialized: table
      +file_format: parquet
